# Set a new pose for the robot.

# for simplicity, since this is a 2d world, we will use our own pose fields
float64 x
float64 y
float64 theta
---

# True if the pose was successfully set, false otherwise.
bool success
