/**:
  ros__parameters:
    # 2x2 measurement covariance matrix (row-major)
    slam_R: [5.0, 0.0,
             0.0, 2.0]

    # 3x3 process covariance robot-pose block [theta, x, y] (row-major)
    # Landmark blocks are auto-filled with zeros in DDSLAM constructor
    slam_Q: [0.002, 0.0, 0.0,
             0.0, 0.001, 0.0,
             0.0, 0.0, 0.001]

    slam_n_max_landmarks: 20
    slam_new_landmark_variance: 100.0
    slam_mahalanobis_association_threshold: 0.2
    slam_mahalanobis_provisional_observation_count: 5

    # Landmark detection parameters
    detector:
      distance_threshold: 0.18
      rmse_threshold: 0.4
      inscribed_angle_mean_range_deg: [70.0, 150.0]
      inscribed_angle_stddev_threshold_deg: 60.0
      min_cluster_size: 5
      concavity_threshold: 0.02
      # concavity_threshold: 1.0  # ignore