/**:
  ros__parameters:
    obstacles:
      x: [1.6, 2.45, -1.5, 0.25, 2.0, -0.85, 1.4, -2.1, 0.45]
      y: [-1.95, 1.0, 1.5, -1.0, -2.0, 0.8, -0.7, -0.4, 2.15]
      r: 0.15
    x0: 0.0
    y0: 0.0
    theta0: 0.0

    arena_x_length: 5.0
    arena_y_length: 5.0

    max_path_size: 10000