/**:
  ros__parameters:
    # m
    wheel_radius: 0.033
    # m
    track_width: 0.16
    motor_cmd_max: 265
    motor_cmd_per_rad_sec: 0.024
    # 12-bit encoder, so 2^12 for a full revolution. 2^12/(2pi) = 
    encoder_ticks_per_rad: 651.8986
    collision_radius: 0.11

    # lidar params
    # from docs: https://emanual.robotis.com/docs/en/platform/turtlebot3/appendix_lds_01/
    lidar_range_min: 0.016
    lidar_range_max: 8.0
    lidar_angle_increment: 0.01745 # 1 degree in radians
    lidar_resolution: 0.01
    lidar_noise_variance: 0.005
    
    # obstacle sensor params
    basic_sensor_variance: 0.005
    # simulated sensor max range (m)
    max_range: 4.0